
data_extract:    
  meta:
    topic_names: "meta"
    table_name: "symbol_metadata"
    chunk_size: 5000
    batch_size: 5000
  raw:
    rate_limit: 10
    chunk_delay: 10
    max_workers: 10
    batch_size: 1000
    max_batch_time: 120

process:
  silver_db_path: storage/silver/resampled.duckdb
  gold_save_path: storage/gold/gold.duckdb
  strategies:
    - vegas_channel:
      intervals:
        - 1
        - 3
        - 5
        - 8
        - 13 

mode: "production"
