development:
  data_extract:    
    meta:
      topic_names: "meta"
      table_name: "symbol_metadata"
      chunk_size: 5000
      batch_size: 5000
    raw:
      rate_limit: 10
      chunk_delay: 10
      max_workers: 10
      batch_size: 1000
      max_batch_time: 120
    datastream:
      batch:
        support_resistance: "support_resistance_alert"
        volume_spike: "volume_spike_alert"
      base_interval: 1m
      expireAfterSeconds: 6048000
      window_size: 5
    databatch:
      table_name: "raw"
      base_interval: 1d
  
  process:
    datastream:
      required_intervals:
        - 5m
        - 30m
        - 60m
      expireAfterSeconds: 6048000
      window_size:
        support_resistance: 5
        volume_spike: 10
    databatch:
      processed_db_name: 
        "processed_market_data"
      train_data_repository_collection_name: 
        "trainable_data_repository"
      new_intervals:
        - 1
        - 3
        - 5
        - 8
        - 13
  analytics:
    alert: 
      long_term: "long_term_alert"
      live: "live_streaming_alerts"

    sandbox_results: 
      long_term: "sandbox_data"
      short_term: "sandbox_data"

    candidates:
      long_term: "long_term_candidates"
      short_term: "short_term_candidates"

    trades:
      long_term: "long_term_sandbox_results"
      short_term: "short_term_sandbox_results"

  mode: "production"
