data_extract:    
  meta:
    topic_names: "meta"
    table_name: "test_symbol_metadata"
    chunk_size: 100
    batch_size: 100
    max_workers: 3  # Reduced for Yahoo Finance rate limiting
    delay_between_requests: 1.0  # 1 second delay between symbols
  raw:
    rate_limit: 10
    chunk_delay: 10
    max_workers: 10
    batch_size: 1000
    max_batch_time: 120

process:
  silver_db_path: process/storage/silver/resampled.duckdb
  gold_path: process/storage/gold
  sql_path: process/sql/resample_view.sql
  new_intervals:
    - 1
    - 3
    - 5
    - 8
    - 13
    - 21
    - 34
    - 55
  strategies:
    vegas_channel:
      intervals:
        - 1
        - 3
        - 5
        - 8
        - 13 
mode: "reset"
